// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2W8gXzuqFItIk-dCJHHvIT9gagjjkfgw',
    appId: '1:863303589265:web:058c956a4942c69bafce30',
    messagingSenderId: '863303589265',
    projectId: 'mopidati',
    authDomain: 'mopidati.firebaseapp.com',
    storageBucket: 'mopidati.appspot.com',
    measurementId: 'G-FHYV8M2HQ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNqnt8s6ydg8rqRpMZc5ntd0ruMJc2fOY',
    appId: '1:863303589265:android:9626f7c6aeb5ffc8afce30',
    messagingSenderId: '863303589265',
    projectId: 'mopidati',
    storageBucket: 'mopidati.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeDaf5f3lQJUqZJFWoKqFMMZqJtfVHZas',
    appId: '1:863303589265:ios:807ac12c36699e58afce30',
    messagingSenderId: '863303589265',
    projectId: 'mopidati',
    storageBucket: 'mopidati.appspot.com',
    iosBundleId: 'com.example.mopidati',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeDaf5f3lQJUqZJFWoKqFMMZqJtfVHZas',
    appId: '1:863303589265:ios:9fc8595ec3389891afce30',
    messagingSenderId: '863303589265',
    projectId: 'mopidati',
    storageBucket: 'mopidati.appspot.com',
    iosBundleId: 'com.example.mopidati.RunnerTests',
  );
}
